### ISSUE TITLE
Recorded Reciepe not working after browser refresh.

### ISSUE THREAD

**Issue by prafulla-samal** [nitinsurana/repeatit#27]
1. Record the reciepe
2.  Refresh the page and go to the page where you started the recording
3. try to apply the recoding , see its not working over there.

**Comment by nitinsurana** [comment]
The version uploaded on google playstore, was connecting to localhost nodejs server, which was incorrect. The reason was that the playstore upload (.zip) was built from `src` folder after executing `gulp dev`. The proper procedure to release a version on playstore is to run `gulp prod` and then zip `src` folder to be uploaded.
